# - Find TinyXML
# Find the native TinyXML includes and library
#
#   TINYXML2_FOUND        - True if TinyXML found.
#   TINYXML2_INCLUDE_DIRS - where to find tinyxml.h, etc.
#   TINYXML2_LIBRARIES    - List of libraries when using TinyXML.
#
#   TINYXML2_VERSION       - Full version of TinyXML.
#   TINYXML2_VERSION_MAJOR - Major version of TinyXML.
#   TINYXML2_VERSION_MINOR - Minor version of TinyXML.
#   TINYXML2_VERSION_PATCH - Patch version of TinyXML.
#

LIST( APPEND TINYXML2_NAMES "tinyxml2" )

FIND_PATH(
  TINYXML2_INCLUDE_DIR
  "tinyxml2.h"
  )
FIND_LIBRARY(
  TINYXML2_LIBRARY
  NAMES ${TINYXML2_NAMES}
  )
MARK_AS_ADVANCED(
  TINYXML2_INCLUDE_DIR
  TINYXML2_LIBRARY
  )

IF( TINYXML2_INCLUDE_DIR AND EXISTS "${TINYXML2_INCLUDE_DIR}/tinyxml.h" )
  FILE(
    STRINGS "${TINYXML2_INCLUDE_DIR}/tinyxml.h"
    TINYXML2_VERSION_MAJOR
    REGEX "^const int TIXML_MAJOR_VERSION = [0-9]+;$"
    )
  FILE(
    STRINGS "${TINYXML2_INCLUDE_DIR}/tinyxml.h"
    TINYXML2_VERSION_MINOR
    REGEX "^const int TIXML_MINOR_VERSION = [0-9]+;$"
    )
  FILE(
    STRINGS "${TINYXML2_INCLUDE_DIR}/tinyxml.h"
    TINYXML2_VERSION_PATCH
    REGEX "^const int TIXML_PATCH_VERSION = [0-9]+;$"
    )

  STRING(
    REGEX REPLACE "^.*TIXML_MAJOR_VERSION = ([0-9]+).*$" "\\1"
    TINYXML2_VERSION_MAJOR "${TINYXML2_VERSION_MAJOR}"
    )
  STRING(
    REGEX REPLACE "^.*TIXML_MINOR_VERSION = ([0-9]+).*$" "\\1"
    TINYXML2_VERSION_MINOR "${TINYXML2_VERSION_MINOR}"
    )
  STRING(
    REGEX REPLACE "^.*TIXML_PATCH_VERSION = ([0-9]+).*$" "\\1"
    TINYXML2_VERSION_PATCH "${TINYXML2_VERSION_PATCH}"
    )

  SET( TINYXML2_VERSION "${TINYXML2_VERSION_MAJOR}.${TINYXML2_VERSION_MINOR}.${TINYXML2_VERSION_PATCH}" )
ENDIF()

SET( TINYXML2_INCLUDE_DIRS "${TINYXML2_INCLUDE_DIR}" )
SET( TINYXML2_LIBRARIES "${TINYXML2_LIBRARY}" )

# handle the QUIETLY and REQUIRED arguments and set TINYXML2_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE( "FindPackageHandleStandardArgs" )
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  "TinyXML2"
  REQUIRED_VARS TINYXML2_LIBRARIES TINYXML2_INCLUDE_DIRS
  VERSION_VAR TINYXML2_VERSION
  )
